import { Route } from '@angular/router';
import { CrmFeatureCampaignsComponent } from './crm-feature-campaigns/crm-feature-campaigns.component';
import { provideStore, provideState } from '@ngrx/store';
import { provideEffects } from '@ngrx/effects';
import * as fromCampaigns from '@apollo-crm/crm/data-access-campaigns';
import { CampaignsEffects } from '@apollo-crm/crm/data-access-campaigns';

export const crmFeatureCampaignsRoutes: Route[] = [
  {
    path: '',
    component: CrmFeatureCampaignsComponent,
    providers: [
      // ** following was generated by NX
      // see below for possible alternative
      provideState(
        fromCampaigns.CAMPAIGNS_FEATURE_KEY,
        fromCampaigns.campaignsReducer
      ),
      provideEffects(CampaignsEffects),
    ],
  },
];

// ** see https://dev.to/ngrx/using-ngrx-packages-with-standalone-angular-features-53d8
// as possible alterative to listed above.

// providers: [
//       // alternative to `StoreModule.forFeature`
//           provideStoreFeature('musicians', musiciansReducer),
//       // alternative to `EffectsModule.forFeature`
//            provideFeatureEffects([MusiciansApiEffects]),
//     ],
